### ISSUE TITLE
[Question] A question about the experimental setup

### ISSUE THREAD

**Issue by 311dada** [ZifanL/TSDS#1]
Congratulations on your excellent work! 

After reading your work, I have a question regarding the experimental setup for task-specific instruction tuning. Specifically, for the three target tasks, do you select the corresponding data for each task and independently train three separate models, or do you mix the tasks, select the data collectively, and train a single model?

Look forward to your response. Thank you!

**Comment by ZifanL** [comment]
Thanks for your interest! For each task, we select data and train a model independently.
